# -*- coding: utf-8 -*-
"""Kmeans++ & k mode clustering .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSB22Qf20iic0EFwDWgu-zgxwCp36im0

**K-Means++ clustering**
"""

import numpy as np
import matplotlib.pyplot as plt

mean_01 = np.array([0.0, 0.0])
cov_01 = np.array([[1, 0.3], [0.3, 1]])
dist_01 = np.random.multivariate_normal(mean_01, cov_01, 100)

mean_02 = np.array([6.0, 7.0])
cov_02 = np.array([[1.5, 0.3], [0.3, 1]])
dist_02 = np.random.multivariate_normal(mean_02, cov_02, 100)

mean_03 = np.array([7.0, -5.0])
dist_03 = np.random.multivariate_normal(mean_03, cov_01, 100)

mean_04 = np.array([2.0, -7.0])
cov_04 = np.array([[1.2, 0.5], [0.5, 1.3]])
dist_04 = np.random.multivariate_normal(mean_04, cov_01, 100)

data = np.vstack((dist_01, dist_02, dist_03, dist_04))
np.random.shuffle(data)

plt.scatter(data[:,0],data[:,1],marker='*',color='blue')

def plot(data, centroids):
    plt.scatter(data[:, 0], data[:, 1], marker='.', color='gray', label='Data Points')
    if centroids.shape[0] > 1:
        plt.scatter(centroids[:-1, 0], centroids[:-1, 1], color='black', label='Selected Centroids')
    plt.scatter(centroids[-1, 0], centroids[-1, 1], color='red', label='Next Centroid')
    plt.title(f'Select {centroids.shape[0]}th Centroid')
    plt.legend()
    plt.xlim(-5, 12)
    plt.ylim(-10, 15)
    plt.show()

def distance(p1, p2):
    return np.sqrt(np.sum((p1 - p2)**2))

import sys

def initialize(data, k):
    centroids = []
    centroids.append(data[np.random.randint(data.shape[0])])
    plot(data, np.array(centroids))

    for _ in range(k - 1):
        distances = []
        for point in data:
            min_dist = min([distance(point, c) for c in centroids])
            distances.append(min_dist)

        distances = np.array(distances)
        probabilities = distances**2 / np.sum(distances**2)

        next_centroid = next_centroid = data[np.random.choice(len(data), p=probabilities)]
        centroids.append(next_centroid)
        plot(data, np.array(centroids))

    return np.array(centroids)

# Run initialization
centroids = initialize(data, k=4)



"""**K - Mode clustering**"""

import numpy as np
import pandas as pd

data = np.array([
    ['Blue','red','black'],
    ['red','black','Blue'],
    ['black','Blue','red'],
    ['black','red','Blue']
])

k = 3

np.random.seed(0)
modes = data[np.random.choice(data.shape[0],k,replace=True)]

clusters = np.zeros(data.shape[0], dtype=int)

for _ in range(10):
    for i, point in enumerate(data):
        distances = [np.sum(point != mode) for mode in modes]
        clusters[i] = np.argmin(distances)

for j in range(k):
        if np.any(clusters == j):
            modes[j] = pd.DataFrame(data[clusters == j]).mode().iloc[0].values

print("Cluster assignments:", clusters)
print("Cluster modes:", modes)

